### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by dlbnco** [jlengstorf/next-image-on-netlify#2]
Jimp does not support SVG, so this is not a total replacement for `next/image`.

However, I managed to tweak the function to just return the SVG, in case you don't need any processing:

```diff
const jimp = require('jimp');

exports.handler = async (event) => {
  const { url, w = 1000, q = 75 } = event.queryStringParameters;
  const width = parseInt(w);
  const quality = parseInt(q);

  const imageUrl = url.startsWith('/')
    ? `${process.env.URL || 'http://localhost:8888'}${url}`
    : URL;

+ const isSvg = url.endsWith('.svg');
+
+ if (isSvg) {
+   return {
+     statusCode: 301,
+     headers: {
+       Location: url,   
+    },
+   };
+ }
  
  const image = await jimp.read(imageUrl);

  image.resize(width, jimp.AUTO).quality(quality);

  const imageBuffer = await image.getBufferAsync(image.getMIME());

  return {
    statusCode: 200,
    headers: {
      'Content-Type': image.getMIME(),
    },
    body: imageBuffer.toString('base64'),
    isBase64Encoded: true,
  };
};
```

**Comment by jlengstorf** [comment]
nice! @ascorbic this might be interesting to you

I believe there's more robust `next/image` than what I have in this demo built into Netlify now, but I'm not sure if SVG has been approached. either way, thank you for sharing this!

I'm going to close since this repo has been replaced by Netlify's native Next.js support

**Comment by ascorbic** [comment]
@jlengstorf This is actually exactly what we already do with SVG and GIF. https://github.com/netlify/netlify-plugin-nextjs/blob/main/src/lib/templates/imageFunction.js#L97-L105
